### ISSUE TITLE
Issues in bulk

### ISSUE THREAD

**Issue by teolemon** [VaiTon/openfoodfacts-explorer#2]
```[tasklist]
### Tasks
- [ ] Add a link to this repository from the interface
- [ ] NOVA distorted + wrong colors
- [ ] Implement a photo manager
- [ ] Implement ingredients editing
- [ ] Implement nutrition editing
- [ ] Add dark mode / light mode toggle in settings
- [ ] Add a clear message when the product does not exist - https://openfoodfacts-explorer.vercel.app/products/123
- [ ] Making this repository an official open food facts project ?
- [ ] Enabling tasklist beta support  https://github.com/features/issues/signup
```

**Comment by lakshaydewan** [comment]
@teolemon  regarding (Add support for Price visualisation on product page), do i make a seperate component like Environment,Health, Report a problem named Pricing? or does it require something else?

**Comment by Sharma-Ji-21** [comment]
@teolemon  @VaiTon , I’d like to start contributing to Open Food Facts Explorer. Since I’m still learning, I’d like to work on two small but impactful issues: “Add a dark mode / light mode toggle in settings” . Let me know if these are good first issues for me to take up. Thanks!

**Comment by VaiTon** [comment]
@Sharma-Ji-21 that's already taken by https://github.com/openfoodfacts/openfoodfacts-explorer/pull/150, for now at least.

**Comment by VaiTon** [comment]
@teolemon what did you mean with "Perform a universal search (OxF) from the barcode scanner" ?

**Comment by akashshetty1997** [comment]
Is the task to design and implement a footer for openfoodfacts-explorer still pending? If yes, I’d be happy to take it up :)
